name: Deploy to gh-pages
on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}